config/routes.rb
Rails.application.routes.draw do

  get 'submissions/index'

  get 'submissions/new'

  get 'submissions/create'

  get 'submissions/destroy'

  get 'submission/index'

  get 'submission/new'

  get 'submission/create'

  get 'submission/destroy'

  root 'welcome#index'

  get '/login' => 'session#new'

  post '/login' => 'session#create'

  delete '/logout' => 'session#destroy', as: :logout

  get '/my_courses' => 'courses#individual_view', as: :dashboard

  get '/enroll_course' => 'courses#enroll', as: :enroll_course

  post '/unenroll_course' => 'courses#unenroll', as: :unenroll_course

  get '/my_assignments' => 'assignments#individual_view', as: :my_assignments

  get '/submit_assignment' => 'submissions#new', as: :submit_assignment

  resources :assignments
  resources :courses
  resources :users
  resources :submissions

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  validates :name, presence: true
  validates :course_id, presence: true
  validates :name, length: { minimum: 2 }
  validates :description, presence: true
  validates :out_of, presence: true
  has_many :CoursesAssignments
  has_many :courses, through: :CoursesAssignments
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  before_action :set_assignment, only: [:show, :edit, :update, :destroy]

  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @student = User.find(session[:user_id])
    @courses = @student.courses
    @course = Course.find(@assignment.course_id)
    @enrolled = @courses.include?(@course)
  end

  # GET /assignments/new
  def new
    @assignment = Assignment.new
  end

  # GET /assignments/1/edit
  def edit; end

  def individual_view
    @student = User.find(session[:user_id])
    @courses = @student.courses
    @assignments = []
    @courses.each do |course|
      @assignments = @assignments + course.assignments
    end
    @assigments = @assignments.sort_by(&:due)
    render :student_assignments
  end

  # POST /assignments
  # POST /assignments.json
  def create
    @assignment = Assignment.new(assignment_params)

    respond_to do |format|
      if @assignment.save
        @course = Course.find(@assignment.course_id)
        @course.assignments.push(@assignment)
        @course.save
        format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
        format.json { render :show, status: :created, location: @assignment }
      else
        format.html { render :new }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assignments/1
  # PATCH/PUT /assignments/1.json
  def update
    respond_to do |format|
      if @assignment.update(assignment_params)
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { render :show, status: :ok, location: @assignment }
      else
        format.html { render :edit }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    all_submissions = Submission.where(assignment_id: @assignment.id)
    all_submissions.each(&:destroy)
    @assignment.destroy
    respond_to do |format|
      format.html { redirect_to assignments_url, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
  def set_assignment
    @assignment = Assignment.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def assignment_params
    params.require(:assignment).permit(:name, :description, :score, :out_of, :course_id, :due, :entry_type)
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.erb
<div class="panel-body">
  <div class="col-md-6">

<%= form_for(@assignment) do |f| %>
  <% if @assignment.errors.any? %>
    <div class="panel panel-danger" role="alert">
      <div class="panel-heading">
        <%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved: 
      </div>
      <div class="panel-body">
        <ul>
        <% @assignment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

    <div class="form-group">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name%>
      </div>
      <div class="field">
        <%= f.label :description %><br>
        <%= f.text_field :description, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :entry_type %><br>
        <%= f.select(:entry_type, [['Exam', 'Exam'], ['Project', 'Project'],['Assignment', 'Assignment']], { :prompt => "Please select"}, { :multiple => false, :size => 3 }) %>
      </div>  
      <div class="field">
        <%= f.label :out_of %><br>
        <%= f.text_field :out_of, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :course %><br>
        <%= f.collection_select :course_id, Course.order(:name),:id,:name, include_blank: false, class: "form-control" %>

      </div>
      <div class="field">
        <%= f.label :due %><br>
        <%= f.datetime_select :due, class: "form-control" %>
      </div>
      <div class="actions">
        <%= f.submit nil, :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/assignments/edit.html.erb
<div class="row">
  	<div class="col-lg-12">
    	<div class="panel panel-default">
      		<div class="panel-heading">Edit Assignment</div>
				<%= render 'form' %>
		</div>
	</div>
</div>

<%= button_to 'Back', assignments_path, :method => :get, class: 'btn btn-primary' %>

app/views/assignments/index.html.erb
<div class="panel panel-success panel-heading" role="alert">
  <p id="notice"><%= notice %></p></div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">All Assignments</div>
      <div class="panel-body">
        <table data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc" id="table-style" data-row-style="rowStyle">
            <thead>
            <tr>
              <th data-sortable="true">Type</th>
              <th data-sortable="true">Name</th>
              <th data-sortable="true">Description</th>
              <th data-sortable="true">Course</th>
              <th data-sortable="true">Due</th>
              <th>More Options</th>
            </tr>
            </thead>

            <tbody>
              <% @assignments.each do |assignment| %>
                <tr>
                  <td><%= assignment.entry_type %></td>
                  <td><%= assignment.name %></td>
                  <td><%= assignment.description %></td>
                  <td><%= Course.find(assignment.course_id).name %></td>
                  <td><%= assignment.due.strftime("%B %C, %Y") %><br><%= assignment.due.strftime("%I:%M%p") %></td>
                  <td><%= button_to 'Show', assignment, :method => :get, class: 'btn btn-success' %><br>
                    <%= button_to 'Edit', edit_assignment_path(assignment), :method => :get, class: 'btn btn-warning' %><br>
                    <%= button_to 'Destroy', assignment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <script>
              $(function () {
                  $('#hover, #striped, #condensed').click(function () {
                      var classes = 'table';

                      if ($('#hover').prop('checked')) {
                          classes += ' table-hover';
                      }
                      if ($('#condensed').prop('checked')) {
                          classes += ' table-condensed';
                      }
                      $('#table-style').bootstrapTable('destroy')
                          .bootstrapTable({
                              classes: classes,
                              striped: $('#striped').prop('checked')
                          });
                  });
              });

              function rowStyle(row, index) {
                  var classes = ['active', 'success', 'info', 'warning', 'danger'];

                  if (index % 2 === 0 && index / 2 < classes.length) {
                      return {
                          classes: classes[index / 2]
                      };
                  }
                  return {};
              }
          </script> 

<br>

<%= button_to 'New Assignment', new_assignment_path, :method => :get, class: 'btn btn-primary' %>

app/views/assignments/new.html.erb
<div class="row">
  	<div class="col-lg-12">
    	<div class="panel panel-default">
      		<div class="panel-heading">New Assignment</div>
				<%= render 'form' %>
		</div>
	</div>
</div>

<%= button_to 'Back', assignments_path, :method => :get, class: 'btn btn-primary' %>

app/views/assignments/show.html.erb
<div class="panel panel-success panel-heading" role="alert">
  <p id="notice"><%= notice %></p></div>

<div class="panel panel-primary">
  <div class="panel-heading"><%= @course.name %> : <%= @assignment.name %></div>

  <p>
    <strong>Description:</strong>
    <%= @assignment.description %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= @assignment.entry_type %>
  </p>

  <p>
    <% if !admin %>
      <strong>Score: </strong>
      <% if Submission.find_by(assignment_id: @assignment.id) != nil && Submission.find_by(assignment_id: @assignment.id).score != nil %>
        <%= Submission.find_by(assignment_id: @assignment.id).score %>
      <% else %>
        Not currently available
      <% end %>
    <% end %>
  </p>

  <p>
    <strong>Out of:</strong>
    <%= @assignment.out_of %>
  </p>

  <p>
    <strong>Due:</strong>
    <%= @assignment.due.strftime("%I:%M%p") %>
  </p>

  <p>
    <% if !admin %>
      <% if @enrolled %>
        <strong>Submission:</strong>
          <% if Submission.find_by(assignment_id: @assignment.id) == nil %>
            <%= link_to 'Submit', submit_assignment_path(:assignment_id => @assignment.id) %>
          <% else %>
            <%= link_to 'View Submission', Submission.find_by(assignment_id: @assignment.id).attachment_url %>
            <%= link_to 'Delete Submission', Submission.find_by(assignment_id: @assignment.id), method: :delete, data: { confirm: 'Are you sure you want to delete this submission?' } %>            
          <% end %>  
      <% end %>
    <% else %>
      <%= link_to 'View All Submissions', submissions_path(:assignment_id => @assignment.id) %>
    <% end %>
  </p>
</div>


<% if admin %>
  <%= button_to 'Edit', edit_assignment_path(@assignment), :method => :get, class: 'btn btn-warning' %><br>
<% end %>
<%= button_to 'Back', assignments_path, :method => :get, class: 'btn btn-primary' %>

app/views/assignments/student_assignments.erb
<div class="panel panel-success panel-heading" role="alert">
  <p id="notice"><%= notice %></p></div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">Upcoming Assignments</div>
      <div class="panel-body">
        <table data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc" id="table-style" data-row-style="rowStyle">
            <thead>
            <tr>
              <th data-sortable="true">Type</th>
              <th data-sortable="true">Name</th>
              <th>Description</th>
              <th data-sortable="true">Course</th>
              <th data-sortable="true">Due</th>
              <th data-align="center">Score</th>
              <th data-align="center">Submission</th>
            </tr>
          </thead>

          <tbody>
            <% @assignments.each do |assignment| %>
              <tr>
                <td><%= assignment.entry_type %></td>
                <td><%= assignment.name %></td>
                <td><%= assignment.description %></td>
                <td><%= Course.find(assignment.course_id).name %></td>
                <td><%= assignment.due.strftime("%B %C, %Y") %><br><%= assignment.due.strftime("%I:%M%p") %></td>
                <td><% if Submission.find_by(assignment_id: assignment.id) != nil && Submission.find_by(assignment_id: assignment.id).score != nil%><%=
                  Submission.find_by(assignment_id: assignment.id).score %>
                  <% else %>
                  Not currently available
                  <% end %></td>        
                <td>
                  <% if !admin %>
                    <% if Submission.find_by(assignment_id: assignment.id) == nil %>
                      <%= link_to 'Submit', submit_assignment_path(:assignment_id => assignment.id) %>
                    <% else %>
                      <%= link_to 'Download Submission', Submission.find_by(assignment_id: assignment.id).attachment_url, download: Submission.find_by(assignment_id: assignment.id).attachment_url, target: "blank" %> | 
                      <%= link_to 'Delete Submission', Submission.find_by(assignment_id: assignment.id), method: :delete, data: { confirm: 'Are you sure you want to delete this submission?' } %>            
                    <% end %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <script>
            $(function () {
                $('#hover, #striped, #condensed').click(function () {
                    var classes = 'table';

                    if ($('#hover').prop('checked')) {
                        classes += ' table-hover';
                    }
                    if ($('#condensed').prop('checked')) {
                        classes += ' table-condensed';
                    }
                    $('#table-style').bootstrapTable('destroy')
                        .bootstrapTable({
                            classes: classes,
                            striped: $('#striped').prop('checked')
                        });
                });
            });

            function rowStyle(row, index) {
                var classes = ['active', 'success', 'info', 'warning', 'danger'];

                if (index % 2 === 0 && index / 2 < classes.length) {
                    return {
                        classes: classes[index / 2]
                    };
                }
                return {};
            }
        </script>  
<br>