config/routes.rb
Rails.application.routes.draw do

  get 'submissions/index'

  get 'submissions/new'

  get 'submissions/create'

  get 'submissions/destroy'

  get 'submission/index'

  get 'submission/new'

  get 'submission/create'

  get 'submission/destroy'

  root 'welcome#index'

  get '/login' => 'session#new'

  post '/login' => 'session#create'

  delete '/logout' => 'session#destroy', as: :logout

  get '/my_courses' => 'courses#individual_view', as: :dashboard

  get '/enroll_course' => 'courses#enroll', as: :enroll_course

  post '/unenroll_course' => 'courses#unenroll', as: :unenroll_course

  get '/my_assignments' => 'assignments#individual_view', as: :my_assignments

  get '/submit_assignment' => 'submissions#new', as: :submit_assignment

  resources :assignments
  resources :courses
  resources :users
  resources :submissions

end

app/models/submission.rb
class Submission < ActiveRecord::Base
   mount_uploader :attachment, AttachmentUploader
   validates :name, presence: true
   validates :name, length: { minimum: 2 }
   validates :attachment, presence: true
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  def index
    @submissions = Submission.where(assignment_id: params[:assignment_id])
    @assignment_id = params[:assignment_id]
    p @assignment_id
  end

  def new
    @submission = Submission.new
    @assignment = Assignment.find(params[:assignment_id])
    @student = User.find(session[:user_id])
  end

  def edit
    @submission = Submission.find(params[:id])
    @assignment = Assignment.find(params[:assignment_id])
    @student = User.find(params[:user_id])
  end

  def create
    @submission = Submission.new(submission_params)
    
    if @submission.save
     redirect_to my_assignments_path, notice: "The submission #{@submission.name} has been uploaded."
   else
     render "new"
   end  
 end

 def update
  @submission = Submission.find(params[:id])
  respond_to do |format|
    if @submission.update(submission_params)
      format.html { redirect_to submissions_path(:assignment_id => submission_params[:assignment_id]), notice: 'Score was successfully updated.' }
      format.json { render :show, status: :ok, location: @submission }
    else
      format.html { render :edit }
      format.json { render json: @submission.errors, status: :unprocessable_entity }
    end
  end    
end

def destroy
 @submission = Submission.find(params[:id])
 @submission.destroy    
 redirect_to my_assignments_path, notice:  "The submission #{@submission.name} has been deleted."
end

private
def submission_params
  params.require(:submission).permit(:name, :attachment, :user_id, :assignment_id, :score)
end

end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/submissions/create.html.erb
<h1>Submissions#create</h1>
<p>Find me in app/views/submissions/create.html.erb</p>

app/views/submissions/destroy.html.erb
<h1>Submissions#destroy</h1>
<p>Find me in app/views/submissions/destroy.html.erb</p>

app/views/submissions/edit.html.erb
<h1>Input Score for <%= link_to @assignment.name, @assignment %></h1>

<%= form_for @submission, html: { multipart: true } do |f| %>
<!-- 	<%= f.label :name %>
  	<%= f.text_field :name %>
  	<%= f.label :attachment %>
  	<%= f.file_field :attachment %> -->
  	<%= f.label :New_Score %>
  	<%= f.number_field :score %>
  	<p> Out of: <%= @assignment.out_of %> </p>
  	<%= f.hidden_field :user_id, :value => @student.id %>
 	<%= f.hidden_field :assignment_id, :value => @assignment.id %>
  	<%= f.submit %>
<% end %>

app/views/submissions/index.html.erb
<div class="panel panel-success panel-heading" role="alert">
  <p id="notice"><%= notice %></p></div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">All Submissions</div>
      <div class="panel-body">
        <table data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc" id="table-style" data-row-style="rowStyle">
            <thead>
            <tr>
      <th data-sortable="true">Submitted by:</th>    	
      <th data-sortable="true">Submission Link</th>
      <th data-sortable="true">On Time?</th>
      <th data-sortable="true">Score</th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
      	<td><%= User.find(submission.user_id).name %></td>
        <td><%= link_to submission.name, submission.attachment_url%></td>
        
        <td><% if submission.created_at < Assignment.find(@assignment_id).due %>
        		Yes
        	<% else %>
        		Late!
        	<% end %>
        </td>
        <td>
        	<% if submission.score != nil %> 
        		<%= submission.score %>
        	<% else %>
        		<%= button_to 'Submit Score', edit_submission_path(submission, :assignment_id => submission.assignment_id, :user_id => submission.user_id), method => :post, :params => {:assignment_id => submission, :user_id => submission.user_id}  %>
        	<% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/submissions/new.html.erb
<div class="row">
  	<div class="col-lg-12">
    	<div class="panel panel-default">
      		<div class="panel-heading">New Submission for <%= link_to @assignment.name, @assignment %></div>
				<div class="panel-body">
				  <div class="col-md-6">
					<%= form_for @submission, html: { multipart: true } do |f| %>
						<div class="form-group">
							<div class="field">
					  			<%= f.label :name %>
					  			<%= f.text_field :name %>
					  		</div>
					  		<div class="field">
					  			<%= f.label :attachment %>
					  			<%= f.file_field :attachment %>
					  		</div>
					  		<%= f.hidden_field :user_id, :value => @student.id %>
					  		<%= f.hidden_field :assignment_id, :value => @assignment.id %>
					  		<%= f.submit "Save", class: "btn btn-primary" %>
					  	</div>
					  </div>
					</div>
			  	</div>
			  </div>
			</div>					
					<% end %>