config/routes.rb
Rails.application.routes.draw do

  get 'submissions/index'

  get 'submissions/new'

  get 'submissions/create'

  get 'submissions/destroy'

  get 'submission/index'

  get 'submission/new'

  get 'submission/create'

  get 'submission/destroy'

  root 'welcome#index'

  get '/login' => 'session#new'

  post '/login' => 'session#create'

  delete '/logout' => 'session#destroy', as: :logout

  get '/my_courses' => 'courses#individual_view', as: :dashboard

  get '/enroll_course' => 'courses#enroll', as: :enroll_course

  post '/unenroll_course' => 'courses#unenroll', as: :unenroll_course

  get '/my_assignments' => 'assignments#individual_view', as: :my_assignments

  get '/submit_assignment' => 'submissions#new', as: :submit_assignment

  resources :assignments
  resources :courses
  resources :users
  resources :submissions

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
    @student = User.find(session[:user_id])
    @courses_enrolled = @student.courses
  end

  # GET /courses/1
  # GET /courses/1.json
  def show; end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit; end

  def individual_view
    @student = User.find(session[:user_id])
    @courses = @student.courses
    render :student_courses
  end

  def enroll
    @course = Course.find(params[:id])
    @student = User.find(session[:user_id])
    @course.users.push(@student)
    @course.save

    redirect_to dashboard_path
  end

  def unenroll
    @course = Course.find(params[:id])
    @student = User.find(session[:user_id])
    @course.users.delete(@student)
    @course.assignments do |assignment|
      all_submissions = Submission.where(user_id: @user.id, assignment_id: assignment.id)
      all_submissions.each(&:destroy)
    end

    @course.save
    redirect_to dashboard_path
  end

  # POST /courses
  # POST /courses.json
  def create
    p course_params
    @course = Course.new(course_params)
    weekdays_list = course_params[:weekdays].drop(1)
    @course.weekdays = weekdays_list.join(', ')

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.assignments.each(&:destroy)
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
  def set_course
    @course = Course.find(params[:id])
  end

    # Never trust parameters from the scary internet, only allow the white list through.
  def course_params
    params.require(:course).permit(:name, :professor, :location, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday, :starting_time, :ending_time, :weekdays => [])
  end
  end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<div class="panel-body">
  <div class="col-md-6">

<%= form_for(@course) do |f| %>
  <% if @course.errors.any? %>
    <div class="panel panel-danger" role="alert">
      <div class="panel-heading">
        <%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:
      </div>
      <div class="panel-body">
        <ul>
      <% @course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  </div>
<% end %>

    <div class="form-group">
      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :professor %><br>
        <%= f.text_field :professor, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :location %><br>
        <%= f.text_field :location, class: "form-control"  %>
      </div> 
      <div class="field">
        <%= f.label :weekdays %><br>
        <%= f.select(:weekdays, [['Monday', 'Monday'],
                                      ['Tuesday', 'Tuesday'],
                                      ['Wednesday', 'Wednesday'],
                                      ['Thursday', 'Thursday'],
                                      ['Friday', 'Friday'],
                                      ['Saturday', 'Saturday'],
                                      ['Sunday','Sunday']
                                     ],{ :prompt => "Please select"},
                                       { :multiple => true, :size => 7 }
                                     ) %>
      </div>                     
      <div class="field">
        <%= f.label :starting_time %><br>
        <%= f.time_field :starting_time, class: "form-control"  %>
      </div>
      <div class="field">
        <%= f.label :ending_time %><br>
        <%= f.time_field :ending_time, class: "form-control"  %>
      </div>  
      <div class="actions">
        <%= f.submit nil, :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
      
<% end %>

app/views/courses/edit.html.erb
<div class="row">
  	<div class="col-lg-12">
    	<div class="panel panel-default">
      		<div class="panel-heading">Edit Course</div>
				<%= render 'form' %>
		</div>
	</div>
</div>
<%= button_to 'Back', courses_path, :method => :get, class: 'btn btn-primary' %>

app/views/courses/index.html.erb
<div class="panel panel-success panel-heading" role="alert">
  <p id="notice"><%= notice %></p></div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">All Courses</div>
      <div class="panel-body">
        <table data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc" id="table-style" data-row-style="rowStyle">
            <thead>
            <tr>
              <th data-sortable="true">Name</th>
              <th data-sortable="true">Professor</th>
              <th data-sortable="true">Location</th>
              <th data-sortable="true">Weekdays</th>
              <th data-sortable="true">Starting Time</th>
              <th data-sortable="true">Ending Time</th>
              <th>More Options</th>
              <% if !admin %>
                <th>Enrollment Status</th>
              <% end %>
            </tr>
            </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.name %></td>
        <td><%= course.professor %></td>
        <td><%= course.location %></td>
        <td>
          <%= course.weekdays %>   
        </td>      
        <td><%= course.starting_time.strftime("%I:%M%p") %></td>
        <td><%= course.ending_time.strftime("%I:%M%p") %></td>
        <td><%= button_to 'Show', course, :method => :get, class: 'btn btn-success' %><br>
        <% if admin %>
          <%= button_to 'Edit', edit_course_path(course), :method => :get, class: 'btn btn-warning' %><br>
          <%= button_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %><br>
        <% end %>
        <% if !admin && !@courses_enrolled.include?(course) %>
          <td><%= button_to 'Enroll', enroll_course_path(:id => course.id), :method => :get, :params => {:id => course.id}, class: 'btn btn-primary' %></td>
        <% end %>   
        <% if !admin && @courses_enrolled.include?(course) %>
          <td><%= button_to 'Un-Enroll', unenroll_course_path(:id => course.id), :method => :post, :params => {:id => course.id}, class: 'btn btn-primary' %></td>
        <% end %>              
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if admin %>
  <%= button_to 'New Course', new_course_path, :method => :get, class: 'btn btn-primary' %>
<% end %>

app/views/courses/new.html.erb
<div class="row">
  	<div class="col-lg-12">
    	<div class="panel panel-default">
      		<div class="panel-heading">New Course</div>
				<%= render 'form' %>
		</div>
	</div>
</div>

<%= button_to 'Back', courses_path, :method => :get, class: 'btn btn-primary' %>

app/views/courses/show.html.erb
<div class="panel panel-success panel-heading" role="alert">
  <p id="notice"><%= notice %></p></div>

  <div class="panel panel-primary">
    <div class="panel-heading"><%= @course.name %></div>

    <p>
      <strong>Professor:</strong>
      <%= @course.professor %>
    </p>

    <p>
      <strong>Location:</strong>
      <%= @course.location %>
    </p>

    <p>
      <strong>Weekdays:</strong>
      <%= @course.weekdays %>       
    </p>

    <p>
      <strong>Time:</strong>
      <%= @course.starting_time.strftime("%I:%M%p") %> to <%= @course.ending_time.strftime("%I:%M%p") %>
    </p>

    <p>
      <strong>Assignments:</strong><br>
      <% @course.assignments.each do |assignment| %>
        <%= link_to assignment.name, assignment %>: <%= assignment.description %>
        <br>
        Due on: <%= assignment.due.strftime("%I:%M%p") %>
      <% end %>
    </p>
  </div>

<% if admin %>
  <%= button_to 'Edit', edit_course_path(@course), :method => :get, class: 'btn btn-warning' %> <br>
<% end %>
<%= button_to 'Back', courses_path, :method => :get, class: 'btn btn-primary' %>

app/views/courses/student_courses.erb
<div class="panel panel-success panel-heading" role="alert">
  <p id="notice"><%= notice %></p></div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">My Courses</div>
      <div class="panel-body">
        <table data-toggle="table" data-show-refresh="true" data-show-toggle="true" data-show-columns="true" data-search="true" data-select-item-name="toolbar1" data-pagination="true" data-sort-name="name" data-sort-order="desc" id="table-style" data-row-style="rowStyle">
            <thead>
            <tr>
              <th data-field="name" data-sortable="true">Name</th>
              <th data-sortable="true">Professor</th>
              <th data-sortable="true">Location</th>
              <th data-sortable="true">Weekdays</th>
              <th data-sortable="true">Starting Time</th>
              <th data-sortable="true">Ending Time</th>
              <th data-align="center">More Info</th>
              <th data-align="center">Enrollment Status</th>
            </tr>
            </thead>

            <tbody>
              <% @courses.each do |course| %>
                <tr>
                  <td><%= course.name %></td>
                  <td><%= course.professor %></td>
                  <td><%= course.location %></td>
                  <td><%= course.weekdays %></td>        
                  <td><%= course.starting_time.strftime("%I:%M%p") %></td>
                  <td><%= course.ending_time.strftime("%I:%M%p") %></td>
                  <td><%= button_to 'Details', course, :method => :get, class: 'btn btn-primary' %></td>
                  <td><%= button_to 'Un-enroll', unenroll_course_path(:id => course.id), :method => :post, :params => {:id => course.id}, class: 'btn btn-danger' %></td>
                </tr>
              <% end %>
            </tbody>            
        </table>
        <script>
            $(function () {
                $('#hover, #striped, #condensed').click(function () {
                    var classes = 'table';
        
                    if ($('#hover').prop('checked')) {
                        classes += ' table-hover';
                    }
                    if ($('#condensed').prop('checked')) {
                        classes += ' table-condensed';
                    }
                    $('#table-style').bootstrapTable('destroy')
                        .bootstrapTable({
                            classes: classes,
                            striped: $('#striped').prop('checked')
                        });
                });
            });
        
            function rowStyle(row, index) {
                var classes = ['active', 'success', 'info', 'warning', 'danger'];
        
                if (index % 2 === 0 && index / 2 < classes.length) {
                    return {
                        classes: classes[index / 2]
                    };
                }
                return {};
            }
        </script>        
      </div>
    </div>
  </div>
</div><!--/.row-->  

<br>

<%= link_to 'Browse Course Listings', courses_path %>